from flask import Blueprint, request
from utils.db import get_db, rows_to_dict, row_to_dict
from utils.auth import login_required
from utils.responses import success, created, error, not_found

receipts_bp = Blueprint("receipts", __name__, url_prefix="/api/receipts")


# ── GET /api/receipts ────────────────────────────────────────────────────────
@receipts_bp.route("", methods=["GET"])

def list_receipts():
    supplier_id = request.args.get("supplier_id")
    with get_db() as conn:
        cur = conn.cursor()
        query = """
            SELECT
                r.*,
                p.AmountPaid, p.PaymentMethod, p.ReferenceNumber, p.PaymentDate,
                i.InvoiceNumber, i.InvoiceAmount,
                po.SupplierID, s.SupplierName
            FROM Receipts r
            JOIN Payments p        ON p.PaymentID  = r.PaymentID
            JOIN Invoices i        ON i.InvoiceID  = p.InvoiceID
            JOIN PurchaseOrders po ON po.POID       = i.POID
            JOIN Suppliers s       ON s.SupplierID  = po.SupplierID
            WHERE 1 = 1
        """
        params = []
        if supplier_id:
            query += " AND po.SupplierID = ?"
            params.append(supplier_id)

        query += " ORDER BY r.ReceiptDate DESC"
        cur.execute(query, params)
        return success(rows_to_dict(cur))


# ── POST /api/receipts ───────────────────────────────────────────────────────
# Receipts are auto-generated by usp_RecordPayment / the payments route.
# This endpoint allows manual creation for edge cases (e.g. re-issue).
@receipts_bp.route("", methods=["POST"])

def create_receipt():
    data = request.get_json() or {}
    if not data.get("payment_id"):
        return error("payment_id is required")

    with get_db() as conn:
        cur = conn.cursor()
        cur.execute("SELECT 1 FROM Payments WHERE PaymentID = ?", data["payment_id"])
        if not cur.fetchone():
            return not_found("Payment")

        # Check a receipt doesn't already exist
        cur.execute(
            "SELECT 1 FROM Receipts WHERE PaymentID = ?", data["payment_id"]
        )
        if cur.fetchone():
            return error("A receipt already exists for this payment", 409)

        from datetime import datetime
        receipt_number = data.get(
            "receipt_number",
            f"RCP-{datetime.now().year}-{str(data['payment_id']).zfill(4)}",
        )

        cur.execute(
            """
            INSERT INTO Receipts (PaymentID, ReceiptNumber, ReceiptDate, ReceivedBy, Notes)
            OUTPUT INSERTED.*
            VALUES (?, ?, ISNULL(?, CAST(GETDATE() AS DATE)), ?, ?)
            """,
            data["payment_id"],
            receipt_number,
            data.get("receipt_date"),
            data.get("received_by"),
            data.get("notes"),
        )
        receipt = row_to_dict(cur)

    return created(receipt, "Receipt created")


# ── GET /api/receipts/<id> ───────────────────────────────────────────────────
@receipts_bp.route("/<int:receipt_id>", methods=["GET"])

def get_receipt(receipt_id):
    with get_db() as conn:
        cur = conn.cursor()
        cur.execute(
            """
            SELECT
                r.*,
                p.AmountPaid, p.PaymentMethod, p.ReferenceNumber, p.PaymentDate,
                i.InvoiceNumber, i.InvoiceAmount, i.InvoiceDate,
                po.POID, po.PODate,
                po.SupplierID, s.SupplierName, s.Address, s.Email, s.Phone
            FROM Receipts r
            JOIN Payments p        ON p.PaymentID  = r.PaymentID
            JOIN Invoices i        ON i.InvoiceID  = p.InvoiceID
            JOIN PurchaseOrders po ON po.POID       = i.POID
            JOIN Suppliers s       ON s.SupplierID  = po.SupplierID
            WHERE r.ReceiptID = ?
            """,
            receipt_id,
        )
        receipt = row_to_dict(cur)
        if not receipt:
            return not_found("Receipt")

    return success(receipt)
